### ISSUE TITLE
BC: the 1.3.0 release is the same as 2.0.0 and break compatibility

### ISSUE THREAD

**Issue by j0k3r** [javibravo/simpleue#7]
You released 2.0.0 which introduce a BC but you also release the 1.3.0 with that same BC which is breaking our code. Could you remove the 1.3.0 release & tag from GitHub to BC?

https://github.com/javibravo/simpleue/compare/1.2.0...1.3.0 is the same as https://github.com/javibravo/simpleue/compare/1.2.0...2.0.0

Both release are on the same commit: 3e3508a

Thanks

**Comment by javibravo** [comment]
Done. My fault, I forgot to remove that tag.

**Comment by j0k3r** [comment]
Thanks!
