### ISSUE TITLE
SqsQueue method getQueueUrl should take both queue name and account id

### ISSUE THREAD

**Issue by excellentsyt** [javibravo/simpleue#8]
The class SqsQueue has a method getQueueUrl(). It seems that the aws sqs php sdk need an array rather than a string. Is it a problem when you try to get the url of a queue on AWS SQS server?

**Comment by javibravo** [comment]
It is passing array as argument when calling `getQueueUrl` with the SQS client:

https://github.com/javibravo/simpleue/blob/master/src/Simpleue/Queue/SqsQueue.php#L69
